development:
  adapter: postgresql
  database: rails_content_parser_development
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  database: rails_content_parser_test
  encoding: utf8
  pool: 5
